### ISSUE TITLE
Javascript didn't work in wordpress

### ISSUE THREAD

**Issue by ybinhatem** [TDRA-ae/aegov-dls#37]
I setup the library with WP but the javascript actions didn't work

**Comment by moiz-conceptlz** [comment]
Did you link to the generated JS file with a script tag?

**Comment by ybinhatem** [comment]
how to link with WordPress?

**Comment by moiz-conceptlz** [comment]
Essentially, after installing the package via NPM, you must aim to follow the [Installation Guide](https://designsystem.gov.ae/docs/installation). 

It completely depends on what build system you are using, however, essentially you would link to the aegov-scripts.js either by manually copying the file to your theme folder structure or using webpack to import the file so that is generates the script along with any additional javascript you would like to add.

Link the file then using ```wp_enqueue_script()``` so that it is loaded when the theme generates the output.
